apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sba-course-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sba-course
    spec:
      containers:
        - name: sba-course
          image: webapp:1
          # for local development against minikube registry
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sba-course
  labels:
    app: sba-course
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8080
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: sba-course