apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sba-auth-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sba-auth
    spec:
      containers:
        - name: sba-auth
          image: webapp:1
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: sba-auth
  labels:
    app: sba-auth
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8087
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: sba-auth