apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sba-payment-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: sba-payment
    spec:
      containers:
        - name: sba-payment
          image: webapp:1
          # for local development against minikube registry
          #imagePullPolicy: Never
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: sba-payment
  labels:
    app: sba-payment
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
      targetPort: 8082
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: sba-payment